"""Chunk kb/ and load kb_documents + kb_chunks. Key-independent: embedding is
left NULL and backfilled by a separate script once the OpenAI key arrives; the
tsv sparse index is generated by Postgres on insert.

Idempotent by wipe-and-reload (same decision as the seed scripts: re-seedable
synthetic data, no migrations). Deleting kb_documents cascades to kb_chunks.

Usage:
    python -m ingest.ingest_kb
"""

import asyncio
from pathlib import Path

import asyncpg

from app.config import settings
from retrieval.chunking import chunk_kb

ROOT = Path(__file__).resolve().parent.parent


async def load(conn: asyncpg.Connection) -> dict[str, int]:
    """Wipe and reload the KB tables. Returns chunk counts per document title."""
    docs = chunk_kb(ROOT / "kb")
    counts: dict[str, int] = {}
    async with conn.transaction():
        await conn.execute("DELETE FROM kb_documents")
        for doc in docs:
            doc_id = await conn.fetchval(
                """
                INSERT INTO kb_documents (title, doc_type, publisher, source_url, license_note)
                VALUES ($1, $2, $3, $4, $5)
                RETURNING id
                """,
                doc.title, doc.doc_type, doc.publisher, doc.source_url, doc.license_note,
            )
            await conn.executemany(
                """
                INSERT INTO kb_chunks (document_id, chunk_index, content, token_count, page_ref)
                VALUES ($1, $2, $3, $4, $5)
                """,
                [(doc_id, c.chunk_index, c.content, c.token_count, c.page_ref)
                 for c in doc.chunks],
            )
            counts[doc.title] = len(doc.chunks)
    return counts


async def main() -> None:
    conn = await asyncpg.connect(settings.database_url)
    try:
        counts = await load(conn)
        for title, n in counts.items():
            print(f"{n:4d}  {title}")
        total = sum(counts.values())
        stats = await conn.fetchrow(
            "SELECT round(avg(token_count)) AS avg, min(token_count) AS min, "
            "max(token_count) AS max FROM kb_chunks"
        )
        print(f"\n{total} chunks across {len(counts)} documents "
              f"(tokens avg {stats['avg']}, min {stats['min']}, max {stats['max']}); "
              "embeddings NULL, pending API key")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
