-- FinQuery master data (DML, idempotent via ON CONFLICT DO NOTHING).
-- Lookups generated from fake-data/category-list.md via fake-data/genlib.ENUMS.
-- Budgets are static experiment design: tuned against seeded spending so
-- user1 has a guaranteed over-budget month (May, Travel) and user3 is
-- chronically over on Food & Drinks. See db/SCHEMA_DESIGN.md.

INSERT INTO categories (name) VALUES
    ('Essentials'),
    ('Lifestyle'),
    ('Goals')
ON CONFLICT DO NOTHING;

INSERT INTO subcategories (category_id, name)
SELECT c.id, v.sub FROM (VALUES
    ('Essentials', 'Bills'),
    ('Essentials', 'Groceries'),
    ('Essentials', 'Transport'),
    ('Essentials', 'Medical'),
    ('Essentials', 'EMI'),
    ('Essentials', 'Insurance'),
    ('Essentials', 'Tax'),
    ('Essentials', 'Children'),
    ('Essentials', 'Services'),
    ('Essentials', 'Credit Bill'),
    ('Essentials', 'Support'),
    ('Essentials', 'Top-up'),
    ('Lifestyle', 'Food & Drinks'),
    ('Lifestyle', 'Shopping'),
    ('Lifestyle', 'Home'),
    ('Lifestyle', 'Entertainment'),
    ('Lifestyle', 'Events'),
    ('Lifestyle', 'Travel'),
    ('Lifestyle', 'Personal'),
    ('Lifestyle', 'Fitness'),
    ('Lifestyle', 'Pet Care'),
    ('Lifestyle', 'Subscription'),
    ('Lifestyle', 'Donation'),
    ('Lifestyle', 'Misc'),
    ('Goals', 'Investment'),
    ('Goals', 'Business'),
    ('Goals', 'Savings'),
    ('Goals', 'Gift'),
    ('Goals', 'Lent'),
    ('Goals', 'Hidden Charges'),
    ('Goals', 'Cash Withdrawal'),
    ('Goals', 'Return'),
    ('Goals', 'Self Transfer')
) AS v(cat, sub) JOIN categories c ON c.name = v.cat
ON CONFLICT DO NOTHING;

INSERT INTO spend_types (subcategory_id, name)
SELECT s.id, v.spend FROM (VALUES
    ('Essentials', 'Bills', 'Rent'),
    ('Essentials', 'Bills', 'Electricity'),
    ('Essentials', 'Bills', 'Water'),
    ('Essentials', 'Bills', 'Gas'),
    ('Essentials', 'Bills', 'Phone'),
    ('Essentials', 'Bills', 'Internet'),
    ('Essentials', 'Groceries', 'Staples'),
    ('Essentials', 'Groceries', 'Vegetables'),
    ('Essentials', 'Groceries', 'Fruits'),
    ('Essentials', 'Groceries', 'Meat'),
    ('Essentials', 'Groceries', 'Eggs'),
    ('Essentials', 'Transport', 'Uber'),
    ('Essentials', 'Transport', 'Rapido'),
    ('Essentials', 'Transport', 'Auto'),
    ('Essentials', 'Transport', 'Cab'),
    ('Essentials', 'Transport', 'Train'),
    ('Essentials', 'Transport', 'Fuel'),
    ('Essentials', 'Medical', 'Medicines'),
    ('Essentials', 'Medical', 'Hospital'),
    ('Essentials', 'Medical', 'Clinic'),
    ('Essentials', 'Medical', 'Dentist'),
    ('Essentials', 'Medical', 'Lab Test'),
    ('Essentials', 'EMI', 'House'),
    ('Essentials', 'EMI', 'Vehicle'),
    ('Essentials', 'EMI', 'Education'),
    ('Essentials', 'EMI', 'Electronics'),
    ('Essentials', 'EMI', 'Personal'),
    ('Essentials', 'Insurance', 'Health'),
    ('Essentials', 'Insurance', 'Vehicle'),
    ('Essentials', 'Insurance', 'Life'),
    ('Essentials', 'Insurance', 'Electronics'),
    ('Essentials', 'Insurance', 'Others'),
    ('Essentials', 'Tax', 'Income Tax'),
    ('Essentials', 'Tax', 'GST'),
    ('Essentials', 'Tax', 'Property Tax'),
    ('Essentials', 'Tax', 'Others'),
    ('Essentials', 'Children', 'Nutrition'),
    ('Essentials', 'Children', 'Necessities'),
    ('Essentials', 'Children', 'Toys'),
    ('Essentials', 'Children', 'Medical'),
    ('Essentials', 'Children', 'Care'),
    ('Essentials', 'Services', 'Laundry'),
    ('Essentials', 'Services', 'Tailor'),
    ('Essentials', 'Services', 'Courier'),
    ('Essentials', 'Services', 'Carpenter'),
    ('Essentials', 'Services', 'Plumber'),
    ('Essentials', 'Credit Bill', 'Credit Card'),
    ('Essentials', 'Credit Bill', 'Simpl'),
    ('Essentials', 'Credit Bill', 'Slice'),
    ('Essentials', 'Credit Bill', 'LazyPay'),
    ('Essentials', 'Credit Bill', 'Amazon Pay'),
    ('Essentials', 'Support', 'Parents'),
    ('Essentials', 'Support', 'Spouse'),
    ('Essentials', 'Support', 'Mom'),
    ('Essentials', 'Support', 'Dad'),
    ('Essentials', 'Support', 'Pocket Money'),
    ('Essentials', 'Top-up', 'UPI Lite'),
    ('Essentials', 'Top-up', 'Paytm'),
    ('Essentials', 'Top-up', 'Amazon'),
    ('Essentials', 'Top-up', 'PhonePe'),
    ('Essentials', 'Top-up', 'Others'),
    ('Lifestyle', 'Food & Drinks', 'Eating Out'),
    ('Lifestyle', 'Food & Drinks', 'Take Away'),
    ('Lifestyle', 'Food & Drinks', 'Tea & Coffee'),
    ('Lifestyle', 'Food & Drinks', 'Fast Food'),
    ('Lifestyle', 'Food & Drinks', 'Snacks'),
    ('Lifestyle', 'Shopping', 'Clothes'),
    ('Lifestyle', 'Shopping', 'Footwear'),
    ('Lifestyle', 'Shopping', 'Electronics'),
    ('Lifestyle', 'Shopping', 'Festival'),
    ('Lifestyle', 'Shopping', 'Video Games'),
    ('Lifestyle', 'Home', 'Essentials'),
    ('Lifestyle', 'Home', 'Toiletries'),
    ('Lifestyle', 'Home', 'Decor'),
    ('Lifestyle', 'Home', 'Cleaning'),
    ('Lifestyle', 'Home', 'Upkeep'),
    ('Lifestyle', 'Entertainment', 'Movies'),
    ('Lifestyle', 'Entertainment', 'Shows'),
    ('Lifestyle', 'Entertainment', 'Bowling'),
    ('Lifestyle', 'Entertainment', 'Tickets'),
    ('Lifestyle', 'Entertainment', 'Others'),
    ('Lifestyle', 'Events', 'Party'),
    ('Lifestyle', 'Events', 'Spiritual'),
    ('Lifestyle', 'Events', 'Wedding'),
    ('Lifestyle', 'Events', 'Others'),
    ('Lifestyle', 'Travel', 'Activities'),
    ('Lifestyle', 'Travel', 'Camping'),
    ('Lifestyle', 'Travel', 'Hotel'),
    ('Lifestyle', 'Travel', 'Commute'),
    ('Lifestyle', 'Travel', 'Meals'),
    ('Lifestyle', 'Personal', 'Self-care'),
    ('Lifestyle', 'Personal', 'Grooming'),
    ('Lifestyle', 'Personal', 'Hobbies'),
    ('Lifestyle', 'Personal', 'Vices'),
    ('Lifestyle', 'Personal', 'Therapy'),
    ('Lifestyle', 'Fitness', 'Gym'),
    ('Lifestyle', 'Fitness', 'Badminton'),
    ('Lifestyle', 'Fitness', 'Football'),
    ('Lifestyle', 'Fitness', 'Cricket'),
    ('Lifestyle', 'Fitness', 'Classes'),
    ('Lifestyle', 'Pet Care', 'Food'),
    ('Lifestyle', 'Pet Care', 'Toys'),
    ('Lifestyle', 'Pet Care', 'Grooming'),
    ('Lifestyle', 'Pet Care', 'Vet'),
    ('Lifestyle', 'Pet Care', 'Others'),
    ('Lifestyle', 'Subscription', 'Netflix'),
    ('Lifestyle', 'Subscription', 'Prime'),
    ('Lifestyle', 'Subscription', 'Software'),
    ('Lifestyle', 'Subscription', 'News'),
    ('Lifestyle', 'Subscription', 'Others'),
    ('Lifestyle', 'Donation', 'Donation'),
    ('Lifestyle', 'Misc', 'Tip'),
    ('Lifestyle', 'Misc', 'Verification'),
    ('Lifestyle', 'Misc', 'Forex'),
    ('Lifestyle', 'Misc', 'Deposit'),
    ('Lifestyle', 'Misc', 'Gift Card'),
    ('Goals', 'Investment', 'Mutual Funds'),
    ('Goals', 'Investment', 'Stocks'),
    ('Goals', 'Investment', 'IPO'),
    ('Goals', 'Investment', 'PPF'),
    ('Goals', 'Investment', 'NPS'),
    ('Goals', 'Investment', 'Emergency Fund'),
    ('Goals', 'Investment', 'Retirement'),
    ('Goals', 'Investment', 'House Down Payment'),
    ('Goals', 'Investment', 'Car Purchase'),
    ('Goals', 'Investment', 'Education Fund'),
    ('Goals', 'Investment', 'Wedding Fund'),
    ('Goals', 'Investment', 'Vacation Fund'),
    ('Goals', 'Business', 'Salary'),
    ('Goals', 'Business', 'Inventory'),
    ('Goals', 'Business', 'Rent'),
    ('Goals', 'Business', 'Logistics'),
    ('Goals', 'Business', 'Software')
) AS v(cat, sub, spend)
JOIN categories c ON c.name = v.cat
JOIN subcategories s ON s.category_id = c.id AND s.name = v.sub
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------ users
INSERT INTO users (username, persona) VALUES
    ('user1', 'familyMan'),
    ('user2', 'gigFreelancer'),
    ('user3', 'youngRenter')
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------ budgets
-- Category-level rows have sub = NULL. Category totals intentionally leave
-- headroom over the sum of subcategory rows (unbudgeted subcategories).
INSERT INTO budgets (user_id, category_id, subcategory_id, monthly_budget)
SELECT u.id, c.id, s.id, v.amt
FROM (VALUES
    -- user1 familyMan: salary 1L; May Travel blowout, Groceries/Children run hot
    ('user1', 'Essentials', NULL,            82000.00),
    ('user1', 'Essentials', 'EMI',           29000.00),
    ('user1', 'Essentials', 'Groceries',      9000.00),
    ('user1', 'Essentials', 'Children',       8000.00),
    ('user1', 'Essentials', 'Credit Bill',    8000.00),
    ('user1', 'Essentials', 'Transport',      6000.00),
    ('user1', 'Essentials', 'Support',        5000.00),
    ('user1', 'Essentials', 'Insurance',      5000.00),
    ('user1', 'Essentials', 'Bills',          4500.00),
    ('user1', 'Essentials', 'Services',       3500.00),
    ('user1', 'Essentials', 'Medical',        1500.00),
    ('user1', 'Lifestyle',  NULL,             9000.00),
    ('user1', 'Lifestyle',  'Food & Drinks',  2000.00),
    ('user1', 'Lifestyle',  'Travel',         1500.00),
    ('user1', 'Lifestyle',  'Shopping',       1500.00),
    ('user1', 'Lifestyle',  'Entertainment',  1200.00),
    ('user1', 'Lifestyle',  'Home',           1200.00),
    ('user1', 'Lifestyle',  'Subscription',    900.00),
    ('user1', 'Goals',      NULL,            15000.00),
    ('user1', 'Goals',      'Investment',    12500.00),
    ('user1', 'Goals',      'Cash Withdrawal', 2500.00),
    -- user2 gigFreelancer: irregular income; mostly within budget
    ('user2', 'Essentials', NULL,            40000.00),
    ('user2', 'Essentials', 'Bills',         21500.00),
    ('user2', 'Essentials', 'Tax',            5000.00),
    ('user2', 'Essentials', 'EMI',            4500.00),
    ('user2', 'Essentials', 'Groceries',      3500.00),
    ('user2', 'Essentials', 'Transport',      2200.00),
    ('user2', 'Essentials', 'Insurance',      2000.00),
    ('user2', 'Essentials', 'Medical',         800.00),
    ('user2', 'Lifestyle',  NULL,            10000.00),
    ('user2', 'Lifestyle',  'Food & Drinks',  3000.00),
    ('user2', 'Lifestyle',  'Subscription',   3000.00),
    ('user2', 'Lifestyle',  'Home',           1500.00),
    ('user2', 'Lifestyle',  'Shopping',       1200.00),
    ('user2', 'Lifestyle',  'Personal',       1000.00),
    ('user2', 'Goals',      NULL,            20000.00),
    ('user2', 'Goals',      'Business',      15000.00),
    ('user2', 'Goals',      'Investment',     5000.00),
    -- user3 youngRenter: chronically over on Lifestyle, esp. Food & Drinks
    ('user3', 'Essentials', NULL,            37000.00),
    ('user3', 'Essentials', 'Bills',         17500.00),
    ('user3', 'Essentials', 'Credit Bill',   14000.00),
    ('user3', 'Essentials', 'Groceries',      2500.00),
    ('user3', 'Essentials', 'Transport',      2200.00),
    ('user3', 'Essentials', 'Medical',         500.00),
    ('user3', 'Lifestyle',  NULL,            20000.00),
    ('user3', 'Lifestyle',  'Food & Drinks',  8000.00),
    ('user3', 'Lifestyle',  'Fitness',        2500.00),
    ('user3', 'Lifestyle',  'Personal',       2000.00),
    ('user3', 'Lifestyle',  'Shopping',       2000.00),
    ('user3', 'Lifestyle',  'Pet Care',       1500.00),
    ('user3', 'Lifestyle',  'Home',           1500.00),
    ('user3', 'Lifestyle',  'Entertainment',  1000.00),
    ('user3', 'Lifestyle',  'Travel',         1000.00),
    ('user3', 'Lifestyle',  'Subscription',    800.00),
    ('user3', 'Lifestyle',  'Events',          700.00),
    ('user3', 'Goals',      NULL,             6500.00),
    ('user3', 'Goals',      'Self Transfer',  5000.00),
    ('user3', 'Goals',      'Lent',           1000.00),
    ('user3', 'Goals',      'Gift',            500.00)
) AS v(username, cat, sub, amt)
JOIN users u ON u.username = v.username
JOIN categories c ON c.name = v.cat
LEFT JOIN subcategories s ON s.category_id = c.id AND s.name = v.sub
ON CONFLICT DO NOTHING;
