"""Approach B: single tool-calling agent (Pydantic AI, gpt-4o-mini).

One agent, six typed tools, visible ReAct loop. Numbers are computed by SQL,
never generated by the LLM.

Boundaries wired here:
- user_id is server-bound via deps; the model cannot choose whose data it sees.
- Every tool result passes _gate(): pseudonymized when PII_MASKING is on,
  logged to llm_payload_log either way. The user question passes the same
  gate before it reaches the model.
- UsageLimits(request_limit) stops runaway loops; retries=2 caps how often a
  ModelRetry (bad taxonomy name, malformed date) can bounce per tool.

The Agent is built WITHOUT a model, so importing this module never needs the
OpenAI key: the live model is created lazily in run_agent, and tests inject
TestModel/FunctionModel through the model parameter.

Reverse mapping is out of scope (design doc): answers may contain fake values
where the narration carried PII; consistency across calls is guaranteed by
the persisted pii_mappings.
"""

import time

from pydantic import BaseModel
from pydantic_ai import Agent, RunContext
from pydantic_ai.usage import UsageLimits

from app.config import settings
from app.db import get_pool
from app.schemas import Citation, RunResult
from agent.deps import AgentDeps, build_deps
from pii.boundary import gate_text, log_payload, persist_mappings
from agent.tools import (
    budget_vs_actual as _budget_vs_actual,
    income_summary as _income_summary,
    search_transactions as _search_transactions,
    spending_by_category as _spending_by_category,
    top_merchants as _top_merchants,
)
from agent.tools.search_finance_kb import search_finance_kb as _search_finance_kb
from guardrails.refusal import REFUSAL_CRITERIA, is_refusal

REQUEST_LIMIT = 10          # hard stop for the ReAct loop, prompt-injection-proof
MAX_QUESTION_CHARS = 1000   # mirrors AskRequest; enforced here too for direct callers

STATIC_INSTRUCTIONS = f"""\
You are FinQuery, a grounded personal-finance assistant for a user in India. \
You answer questions about the user's own bank transactions and about core \
personal-finance concepts. Amounts are Indian Rupees (INR).

## Grounding rules

- Every number in your answer must come from a tool result. Never add, \
subtract, average, or estimate amounts yourself; if you need a total, call \
the tool that computes it. For monthly averages or month-by-month trends, \
call spending_by_category with group_by_month=true; it returns per-month \
totals and the monthly average, already computed.
- Transaction data covers 2026-01-01 to 2026-06-30. If asked about dates \
outside this range, say the data does not cover them.
- Use search_finance_kb for concepts, product categories, and rules of thumb; \
answer from the retrieved passages and say so if they do not cover the question.
- If a question needs both the user's numbers and a concept (for example \
"is my EMI ratio healthy"), call the data tools and the KB tool, then combine.
- When advising on the user's situation, do all three: find the specific \
transactions driving the issue (drill down with search_transactions when a \
category total looks unusual), fetch the relevant guideline from the KB, and \
apply that guideline to the user's actual numbers, not just state it.
- When asked to exclude something (for example "expenses other than EMI"), \
check that what you cite actually respects the exclusion.
- Be factual and complete: for concept questions, cover every distinct point \
the retrieved passages make about the question, briefly. State the date range \
a number covers.

{REFUSAL_CRITERIA}"""


agent: Agent[AgentDeps, str] = Agent(
    deps_type=AgentDeps,
    retries=2,
    instructions=STATIC_INSTRUCTIONS,
)

_taxonomy_section: str | None = None


@agent.instructions
async def taxonomy_instructions(ctx: RunContext[AgentDeps]) -> str:
    """The fixed category taxonomy, read once per process from the lookup
    tables so the prompt never drifts from the seeded data."""
    global _taxonomy_section
    if _taxonomy_section is None:
        pool = await get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """SELECT c.name AS category, s.name AS subcategory
                   FROM subcategories s JOIN categories c ON c.id = s.category_id
                   ORDER BY c.id, s.name"""
            )
        by_cat: dict[str, list[str]] = {}
        for r in rows:
            by_cat.setdefault(r["category"], []).append(r["subcategory"])
        lines = [f"- {cat}: {', '.join(subs)}" for cat, subs in by_cat.items()]
        _taxonomy_section = (
            "## Category taxonomy (fixed, use these exact names in tool calls)\n\n"
            + "\n".join(lines)
        )
    return _taxonomy_section


# --------------------------------------------------------------- LLM boundary

async def _gate(ctx: RunContext[AgentDeps], tool_name: str, args: dict,
                result: BaseModel) -> str:
    """Single choke point between tool results and LLM context: pseudonymize
    (when PII_MASKING is on), log the exact LLM-bound payload, record the call."""
    args = {k: v for k, v in args.items() if v is not None}
    payload = await gate_text(ctx.deps.pseudonymizer, result.model_dump_json())
    await log_payload(ctx.deps.user_id, "agent", "tool_result", payload)
    ctx.deps.tool_calls.append({"tool": tool_name, "args": args})
    return payload


# ------------------------------------------------- tools (user_id from deps)

@agent.tool
async def spending_by_category(
    ctx: RunContext[AgentDeps],
    category: str | None = None,
    subcategory: str | None = None,
    spend_type: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    group_by_month: bool = False,
) -> str:
    """Total debit spending for the user, optionally filtered by taxonomy and dates.

    Args:
        category: Optional category name (Essentials, Lifestyle, Goals).
        subcategory: Optional subcategory name, e.g. 'Groceries', 'EMI', 'Travel'.
        spend_type: Optional spend type name, e.g. 'Fuel', 'Mutual Funds'.
        start_date: ISO date YYYY-MM-DD; defaults to the start of available data.
        end_date: ISO date YYYY-MM-DD, inclusive; defaults to the end of available data.
        group_by_month: If true, also return per-month totals and the monthly
            average over the calendar months in the range. Use this for monthly
            averages and month-by-month trends.
    """
    args = dict(category=category, subcategory=subcategory, spend_type=spend_type,
                start_date=start_date, end_date=end_date,
                group_by_month=group_by_month or None)  # recorded only when set
    result = await _spending_by_category(
        ctx.deps.user_id, **{**args, "group_by_month": group_by_month})
    ctx.deps.citations.append(Citation(
        kind="sql_tool", ref="spending_by_category",
        detail=f"{result.txn_count} transactions, {result.start_date} to {result.end_date}",
    ))
    return await _gate(ctx, "spending_by_category", args, result)


@agent.tool
async def budget_vs_actual(
    ctx: RunContext[AgentDeps],
    month: str,
    category: str | None = None,
) -> str:
    """Compare budgeted amounts against actual debit spending for one month.

    Args:
        month: Month to compare, format YYYY-MM, e.g. '2026-05'.
        category: Optional category name to narrow the report (Essentials, Lifestyle, Goals).
    """
    args = dict(month=month, category=category)
    result = await _budget_vs_actual(ctx.deps.user_id, **args)
    ctx.deps.citations.append(Citation(
        kind="sql_tool", ref="budget_vs_actual",
        detail=f"{len(result.lines)} budget lines for {result.month}",
    ))
    return await _gate(ctx, "budget_vs_actual", args, result)


@agent.tool
async def top_merchants(
    ctx: RunContext[AgentDeps],
    start_date: str | None = None,
    end_date: str | None = None,
    limit: int = 5,
) -> str:
    """Rank merchants/counterparties by total debit spend over a date range.

    Args:
        start_date: ISO date YYYY-MM-DD; defaults to the start of available data.
        end_date: ISO date YYYY-MM-DD, inclusive; defaults to the end of available data.
        limit: How many merchants to return (1-25, default 5).
    """
    args = dict(start_date=start_date, end_date=end_date, limit=limit)
    result = await _top_merchants(ctx.deps.user_id, **args)
    ctx.deps.citations.append(Citation(
        kind="sql_tool", ref="top_merchants",
        detail=f"top {len(result.merchants)}, {result.start_date} to {result.end_date}",
    ))
    return await _gate(ctx, "top_merchants", args, result)


@agent.tool
async def income_summary(
    ctx: RunContext[AgentDeps],
    start_date: str | None = None,
    end_date: str | None = None,
) -> str:
    """Summarize all credits (salary, interest, refunds) for the user over a date range.

    Args:
        start_date: ISO date YYYY-MM-DD; defaults to the start of available data.
        end_date: ISO date YYYY-MM-DD, inclusive; defaults to the end of available data.
    """
    args = dict(start_date=start_date, end_date=end_date)
    result = await _income_summary(ctx.deps.user_id, **args)
    ctx.deps.citations.append(Citation(
        kind="sql_tool", ref="income_summary",
        detail=f"{result.txn_count} credits, {result.start_date} to {result.end_date}",
    ))
    return await _gate(ctx, "income_summary", args, result)


@agent.tool
async def search_transactions(
    ctx: RunContext[AgentDeps],
    text: str | None = None,
    category: str | None = None,
    subcategory: str | None = None,
    txn_type: str | None = None,
    min_amount: float | None = None,
    max_amount: float | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    order_by: str = "date",
    limit: int = 20,
) -> str:
    """Search individual transactions with filters; returns matching rows.

    Args:
        text: Optional case-insensitive words matched against the bank narration;
            every word must appear, in any order.
        category: Optional category name (Essentials, Lifestyle, Goals).
        subcategory: Optional subcategory name, e.g. 'Groceries', 'EMI'.
        txn_type: Optional 'credit' or 'debit'.
        min_amount: Optional lower bound on amount.
        max_amount: Optional upper bound on amount.
        start_date: ISO date YYYY-MM-DD; defaults to the start of available data.
        end_date: ISO date YYYY-MM-DD, inclusive; defaults to the end of available data.
        order_by: 'date' (newest first, default) or 'amount' (largest first).
        limit: Max rows to return (1-50, default 20).
    """
    args = dict(text=text, category=category, subcategory=subcategory,
                txn_type=txn_type, min_amount=min_amount, max_amount=max_amount,
                start_date=start_date, end_date=end_date, order_by=order_by, limit=limit)
    result = await _search_transactions(ctx.deps.user_id, **args)
    ctx.deps.citations.append(Citation(
        kind="sql_tool", ref="search_transactions",
        detail=f"{result.returned} of {result.total_matches} matching transactions",
    ))
    return await _gate(ctx, "search_transactions", args, result)


@agent.tool
async def search_finance_kb(
    ctx: RunContext[AgentDeps],
    query: str,
    limit: int = 5,
) -> str:
    """Search the personal-finance knowledge base (RBI/NCFE investor-education
    material and original articles) for concepts, rules of thumb, and how
    financial products work.

    Args:
        query: What to look up, e.g. 'emergency fund size' or '50/30/20 rule'.
        limit: Max chunks to return (1-10, default 5).
    """
    args = dict(query=query, limit=limit)
    result = await _search_finance_kb(**args)
    for hit in result.hits:
        ctx.deps.citations.append(Citation(
            kind="kb_chunk",
            ref=f"{hit.document_title} (chunk {hit.chunk_id})",
            detail=hit.page_ref or "",
        ))
    return await _gate(ctx, "search_finance_kb", args, result)


# ---------------------------------------------------------------- entry point

def _live_model():
    """Built lazily so importing this module (and offline tests) never needs
    the OpenAI key."""
    if not settings.openai_api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is empty in .env; pass a test model or configure the key."
        )
    from pydantic_ai.models.openai import OpenAIChatModel
    from pydantic_ai.providers.openai import OpenAIProvider

    return OpenAIChatModel(
        settings.llm_model, provider=OpenAIProvider(api_key=settings.openai_api_key)
    )


async def run_agent(question: str, user_id: int, model=None) -> RunResult:
    """Answer one question for one user. model is injected by tests
    (TestModel/FunctionModel); None means the live configured LLM."""
    if not question.strip():
        raise ValueError("question is empty")
    if len(question) > MAX_QUESTION_CHARS:
        raise ValueError(f"question exceeds {MAX_QUESTION_CHARS} characters")
    model = model or _live_model()  # fail on a missing key before any side effects

    deps = await build_deps(user_id)
    question = await gate_text(deps.pseudonymizer, question)

    await log_payload(user_id, "agent", "system", STATIC_INSTRUCTIONS)
    await log_payload(user_id, "agent", "user", question)

    started = time.monotonic()
    result = await agent.run(
        question,
        deps=deps,
        model=model,
        usage_limits=UsageLimits(request_limit=REQUEST_LIMIT),
    )
    latency_ms = int((time.monotonic() - started) * 1000)

    answer = result.output
    await log_payload(user_id, "agent", "answer", answer, direction="from_llm")

    return RunResult(
        answer=answer,
        refused=is_refusal(answer),
        citations=deps.citations,
        tool_calls=deps.tool_calls,
        latency_ms=latency_ms,
    )
