"""Approach B: single tool-calling agent (Pydantic AI, gpt-4o-mini).

One agent, six typed tools, visible ReAct loop. Numbers are computed by SQL,
never generated by the LLM. Every tool output passes through the PII
pseudonymization gate (pii/) before entering LLM context.

Implemented after the OpenAI API key arrives (key-dependent step).
"""
